apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::304534110140:role/eksctl-brain-task-cluster-nodegrou-NodeInstanceRole-BFotyyxHmX9L
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::304534110140:role/codebuild-brain-task-service-role
      username: build
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-20T03:17:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "35753"
  uid: 9adfde46-65ac-4c2f-9156-1369fb9a25fe
